### ISSUE TITLE
Helptext doesn't match definition

### ISSUE THREAD

**Issue by zrh535** [foex-open-source/fos-message-actions#1]
> Auto Dismiss Message(s)
    Select this option (and execute it on Page Load) to automatically dismiss success/error messages after a specified time - set the "hideAfter" property in the JavaScript Initialization Code to the required value in milliseconds. Default is 3000. 

Setting the timer threshold appears to be a declarative attribute now, rather than requiring the JavaScript Initialization code. This help text also mentions that the default is 3000 milliseconds, but the defaults for the 2 declarative attributes are set to 5 seconds and 10 seconds.

**Comment by foex-open-source** [comment]
Thanks for reporting the issue, it's fixed with v22.1.
